/// Dialect codegen — parsed .synth dialects → Rust source.
///
/// Emits Rust code that constructs Vec<Dialect> using the types
/// from askicc::synth_parse. askic imports askicc as a crate.

use crate::synth_parse::*;

trait EmitRust {
    fn emit_rust(&self, out: &mut String);
}

impl EmitRust for Dialect {
    fn emit_rust(&self, out: &mut String) {
        out.push_str(&format!("        Dialect {{\n"));
        out.push_str(&format!("            name: \"{}\".to_string(),\n", self.name));
        out.push_str(&format!("            rules: vec![\n"));
        for rule in &self.rules {
            out.push_str("                ");
            rule.emit_rust(out);
            out.push_str(",\n");
        }
        out.push_str("            ],\n");
        out.push_str("        }");
    }
}

impl EmitRust for Rule {
    fn emit_rust(&self, out: &mut String) {
        match self {
            Rule::Sequential(items) => {
                out.push_str("Rule::Sequential(vec![");
                for item in items { item.emit_rust(out); out.push_str(", "); }
                out.push_str("])");
            }
            Rule::OrderedChoice(alts) => {
                out.push_str("Rule::OrderedChoice(vec![");
                for alt in alts { alt.emit_rust(out); out.push_str(", "); }
                out.push_str("])");
            }
        }
    }
}

impl EmitRust for Alternative {
    fn emit_rust(&self, out: &mut String) {
        out.push_str("Alternative { items: vec![");
        for item in &self.items { item.emit_rust(out); out.push_str(", "); }
        out.push_str(&format!("], cardinality: {} }}", self.cardinality.emit_str()));
    }
}

impl EmitRust for Item {
    fn emit_rust(&self, out: &mut String) {
        out.push_str(&format!("Item {{ content: {}, adjacent: {} }}",
            self.content.to_rust_str(), self.adjacent));
    }
}

impl ItemContent {
    fn to_rust_str(&self) -> String {
        match self {
            ItemContent::Declare { casing, label } =>
                format!("ItemContent::Declare {{ casing: {}, label: \"{}\".to_string() }}",
                    casing.emit_str(), label),
            ItemContent::DialectRef(name) =>
                format!("ItemContent::DialectRef(\"{}\".to_string())", name),
            ItemContent::Delimited { kind, inner } => {
                let mut items = String::from("vec![");
                for item in inner {
                    items.push_str(&format!("Item {{ content: {}, adjacent: {} }}, ",
                        item.content.to_rust_str(), item.adjacent));
                }
                items.push(']');
                format!("ItemContent::Delimited {{ kind: {}, inner: {} }}",
                    kind.emit_str(), items)
            }
            ItemContent::Literal(s) =>
                format!("ItemContent::Literal(\"{}\".to_string())",
                    s.replace('\\', "\\\\").replace('"', "\\\"")),
            ItemContent::Repeat { kind, inner } =>
                format!("ItemContent::Repeat {{ kind: {}, inner: Box::new(Item {{ content: {}, adjacent: {} }}) }}",
                    kind.emit_str(), inner.content.to_rust_str(), inner.adjacent),
            ItemContent::LiteralValue => "ItemContent::LiteralValue".to_string(),
        }
    }
}

impl Cardinality {
    fn emit_str(&self) -> &'static str {
        match self {
            Cardinality::One => "Cardinality::One",
            Cardinality::ZeroOrMore => "Cardinality::ZeroOrMore",
            Cardinality::OneOrMore => "Cardinality::OneOrMore",
            Cardinality::Optional => "Cardinality::Optional",
        }
    }
}

impl Casing {
    fn emit_str(&self) -> &'static str {
        match self { Casing::Pascal => "Casing::Pascal", Casing::Camel => "Casing::Camel" }
    }
}

impl DelimKind {
    fn emit_str(&self) -> &'static str {
        match self {
            DelimKind::Paren => "DelimKind::Paren",
            DelimKind::Bracket => "DelimKind::Bracket",
            DelimKind::Brace => "DelimKind::Brace",
            DelimKind::ParenPipe => "DelimKind::ParenPipe",
            DelimKind::BracketPipe => "DelimKind::BracketPipe",
            DelimKind::BracePipe => "DelimKind::BracePipe",
        }
    }
}

/// Emit the complete dialects module as Rust source.
pub struct DialectCodegen<'a> {
    pub dialects: &'a [Dialect],
}

impl<'a> DialectCodegen<'a> {
    pub fn emit(&self) -> String {
        let mut out = String::new();
        out.push_str("// Generated by askicc from .synth dialect files.\n");
        out.push_str("// Do not edit — regenerate with `askicc`.\n\n");
        out.push_str("use askicc::synth_parse::*;\n\n");
        out.push_str("pub fn all_dialects() -> Vec<Dialect> {\n");
        out.push_str("    vec![\n");
        for dialect in self.dialects {
            dialect.emit_rust(&mut out);
            out.push_str(",\n");
        }
        out.push_str("    ]\n");
        out.push_str("}\n");
        out
    }
}
