/// askicc — the bootstrap compiler.
///
/// Reads .synth dialect files and .aski domain definitions.
/// Emits Rust: scoped types (enum-as-index) + dialect structures.
/// Both are compiled into askic.

use std::fs;
use std::path::Path;

use askicc::synth_lex;
use askicc::synth_parse::Dialect;
use askicc::aski_parse::Module;
use askicc::codegen::RustOutput;

fn main() {
    let synth_dir = Path::new("source");
    let aski_dir = Path::new("aski");
    let out_dir = Path::new("generated");

    fs::create_dir_all(out_dir).expect("failed to create output directory");

    // Phase 1: Parse .synth dialect files
    let mut dialects = Vec::new();
    let mut synth_files: Vec<_> = fs::read_dir(synth_dir)
        .expect("failed to read source/ directory")
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map(|x| x == "synth").unwrap_or(false))
        .collect();
    synth_files.sort_by_key(|e| e.path());

    for entry in &synth_files {
        let path = entry.path();
        let name = path.file_stem().unwrap().to_string_lossy().to_string();
        let source = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("failed to read {}: {}", path.display(), e));

        let tokens = synth_lex::synth_lex(&source)
            .unwrap_or_else(|e| panic!("synth lex error in {}: {}", path.display(), e));

        let dialect = Dialect::parse(&name, &tokens)
            .unwrap_or_else(|e| panic!("synth parse error in {}: {}", path.display(), e));

        eprintln!("askicc: synth {} → {} rules", name, dialect.rules.len());
        dialects.push(dialect);
    }

    // Phase 2: Parse .aski domain definitions
    let mut modules = Vec::new();
    let mut aski_files: Vec<_> = fs::read_dir(aski_dir)
        .expect("failed to read aski/ directory")
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map(|x| x == "aski").unwrap_or(false))
        .collect();
    aski_files.sort_by_key(|e| e.path());

    for entry in &aski_files {
        let path = entry.path();
        let source = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("failed to read {}: {}", path.display(), e));

        let module = Module::parse(&source)
            .unwrap_or_else(|e| panic!("aski parse error in {}: {}", path.display(), e));

        eprintln!("askicc: aski {} → {} domains", module.name, module.domains.len());
        modules.push(module);
    }

    // Phase 3: Generate Rust from parsed domains
    let mut all_output = String::new();
    all_output.push_str("// Generated by askicc from .aski domain definitions.\n");
    all_output.push_str("// Do not edit — regenerate with `askicc`.\n\n");

    for module in &modules {
        let rust = RustOutput::from_module(module);
        all_output.push_str(&format!("// — module {} —\n\n", module.name));
        all_output.push_str(&rust.source);
    }

    let types_path = out_dir.join("domain_tree.rs");
    fs::write(&types_path, &all_output)
        .unwrap_or_else(|e| panic!("failed to write {}: {}", types_path.display(), e));
    eprintln!("askicc: wrote {}", types_path.display());

    // Phase 4: Generate Rust from parsed dialects
    let mut dialect_output = String::new();
    dialect_output.push_str("// Generated by askicc from .synth dialect files.\n");
    dialect_output.push_str("// Do not edit — regenerate with `askicc`.\n\n");
    dialect_output.push_str(&format!("pub const DIALECT_COUNT: usize = {};\n\n", dialects.len()));

    for dialect in &dialects {
        dialect_output.push_str(&format!("// dialect: {} ({} rules)\n", dialect.name, dialect.rules.len()));
    }

    let dialect_path = out_dir.join("dialects.rs");
    fs::write(&dialect_path, &dialect_output)
        .unwrap_or_else(|e| panic!("failed to write {}: {}", dialect_path.display(), e));
    eprintln!("askicc: wrote {}", dialect_path.display());

    eprintln!("askicc: done — {} dialects, {} modules", dialects.len(), modules.len());
}
