/// askicc — the bootstrap compiler.
///
/// Reads .synth dialect files and .aski domain definitions.
/// Emits Rust: scoped types (enum-as-index) + dialect structures.

use std::fs;
use std::path::Path;

use askicc::synth_lex;
use askicc::synth_parse::Dialect;
use askicc::aski_parse::Module;
use askicc::codegen::RustOutput;
use askicc::codegen_dialect;

struct Askicc {
    dialects: Vec<Dialect>,
    modules: Vec<Module>,
}

impl Askicc {
    fn load(synth_dir: &Path, aski_dir: &Path) -> Self {
        let dialects = Self::load_dialects(synth_dir);
        let modules = Self::load_modules(aski_dir);
        Askicc { dialects, modules }
    }

    fn load_dialects(dir: &Path) -> Vec<Dialect> {
        let mut files: Vec<_> = fs::read_dir(dir)
            .unwrap_or_else(|e| panic!("failed to read {}: {}", dir.display(), e))
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().map(|x| x == "synth").unwrap_or(false))
            .collect();
        files.sort_by_key(|e| e.path());

        files.iter().map(|entry| {
            let path = entry.path();
            let name = path.file_stem().unwrap().to_string_lossy().to_string();
            let source = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("failed to read {}: {}", path.display(), e));
            let tokens = synth_lex::synth_lex(&source)
                .unwrap_or_else(|e| panic!("synth lex error in {}: {}", path.display(), e));
            let dialect = Dialect::parse(&name, &tokens)
                .unwrap_or_else(|e| panic!("synth parse error in {}: {}", path.display(), e));
            eprintln!("askicc: synth {} → {} rules", name, dialect.rules.len());
            dialect
        }).collect()
    }

    fn load_modules(dir: &Path) -> Vec<Module> {
        let mut files: Vec<_> = fs::read_dir(dir)
            .unwrap_or_else(|e| panic!("failed to read {}: {}", dir.display(), e))
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().map(|x| x == "aski").unwrap_or(false))
            .collect();
        files.sort_by_key(|e| e.path());

        files.iter().map(|entry| {
            let path = entry.path();
            let source = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("failed to read {}: {}", path.display(), e));
            let module = Module::parse(&source)
                .unwrap_or_else(|e| panic!("aski parse error in {}: {}", path.display(), e));
            eprintln!("askicc: aski {} → {} domains", module.name, module.domains.len());
            module
        }).collect()
    }

    fn emit(&self, out_dir: &Path) {
        fs::create_dir_all(out_dir).expect("failed to create output directory");
        self.emit_domain_types(out_dir);
        self.emit_dialects(out_dir);
        eprintln!("askicc: done — {} dialects, {} modules", self.dialects.len(), self.modules.len());
    }

    fn emit_domain_types(&self, out_dir: &Path) {
        let mut out = String::new();
        out.push_str("// Generated by askicc from .aski domain definitions.\n");
        out.push_str("// Do not edit — regenerate with `askicc`.\n\n");

        for module in &self.modules {
            let rust = RustOutput::from_module(module);
            out.push_str(&format!("// — module {} —\n\n", module.name));
            out.push_str(&rust.source);
        }

        let path = out_dir.join("domain_tree.rs");
        fs::write(&path, &out)
            .unwrap_or_else(|e| panic!("failed to write {}: {}", path.display(), e));
        eprintln!("askicc: wrote {}", path.display());
    }

    fn emit_dialects(&self, out_dir: &Path) {
        let codegen = codegen_dialect::DialectCodegen { dialects: &self.dialects };
        let out = codegen.emit();

        let path = out_dir.join("dialects.rs");
        fs::write(&path, &out)
            .unwrap_or_else(|e| panic!("failed to write {}: {}", path.display(), e));
        eprintln!("askicc: wrote {}", path.display());
    }
}

fn main() {
    let compiler = Askicc::load(Path::new("source"), Path::new("aski"));
    compiler.emit(Path::new("generated"));
}
